package ua.taxi.base.model.user;

import ua.taxi.base.model.IdAutoGeneratedEntity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.io.Serializable;

/**
 * Created with IntelliJ IDEA.
 * user: Роман
 * Date: 23.04.16
 * Time: 17:03
 * To change this test use File | Settings | File Templates.
 */

@Entity
@Table(name = "Cars")
public class Car extends IdAutoGeneratedEntity implements Serializable {

    @Column(nullable = false, length = 8 )
    String number;

    @Column(nullable = false, length = 30 )
    String model;

    @Column(nullable = false, length = 30 )
    String color;

    public Car(){}

    public Car(String number, String model, String color) {
        this.number = number;
        this.model = model;
        this.color = color;
    }

    public String getNumber() {
        return number;
    }

    public String getModel() {
        return model;
    }

    public String getColor() {
        return color;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public void setColor(String color) {
        this.color = color;
    }

    @Override
    public String toString() {
        return  number + " " + model + " " + color;
    }

    @Override
    public boolean equals(Object object) {
        if (this == object) return true;
        if (object == null || getClass() != object.getClass()) return false;

        Car car = (Car) object;

        if (!number.equals(car.number)) return false;
        if (!model.equals(car.model)) return false;
        return color.equals(car.color);

    }
}
