package ua.taxi.base.model.user;


import org.hibernate.annotations.*;
import ua.taxi.base.model.IdAutoGeneratedEntity;

import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import java.io.Serializable;

/**
 * Created by serhii on 23.04.16.
 */
@Entity
@Inheritance(strategy = InheritanceType.JOINED)
@DiscriminatorColumn(name = "user_type")
@Table(name = "Users")
@NamedQuery(name="findUserByPhone", query = "SELECT u from User u where u.phone = ?1")
public abstract class User extends IdAutoGeneratedEntity implements Serializable {

    @Column(nullable = false, length = 14, unique = true)
    private String phone;
    @Column(nullable = false, length = 30 )
    private String pass;
    @Column(nullable = false, length = 30 )
    private String name;

    public User(){}

    public User(String phone, String pass, String name) {
        this.phone = phone;
        this.pass = pass;
        this.name = name;
    }

    public String getPhone() {
        return phone;
    }

    public String getPass() {
        return pass;
    }

    public String getName() {
        return name;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public void setPass(String pass) {
        this.pass = pass;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return " user{" +
                "phone='" + phone + '\'' +
                ", pass='" + pass + '\'' +
                ", name='" + name + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object object) {
        if (this == object) return true;
        if (!(object instanceof User)) return false;

        User user = (User) object;

        if (phone != null ? !phone.equals(user.phone) : user.phone != null) return false;
        if (pass != null ? !pass.equals(user.pass) : user.pass != null) return false;
        return name != null ? name.equals(user.name) : user.name == null;

    }

    @Override
    public int hashCode() {
        int result = phone != null ? phone.hashCode() : 0;
        result = 31 * result + (pass != null ? pass.hashCode() : 0);
        result = 31 * result + (name != null ? name.hashCode() : 0);
        return result;
    }
}
