package ua.taxi.test.model;



import javax.persistence.*;
import java.util.Set;

/**
 * Created by andrii on 09.07.16.
 */

@Entity
@Table(name = "courses")
@NamedQueries({@NamedQuery(name = "getAll", query = "SELECT c FROM Course c")})
public class Course extends IdAutoGeneratedEntity{

    @Column(nullable = false)
    private String title;

    private String description;

    @ManyToOne //this one have many
    @JoinColumn(name = "teacher_id", referencedColumnName = "id")
    private Teacher owner;


   // private Set<Student> studentSet;

    public Course(){

    }

    public Course(String title, String description) {
        this.title = title;
        this.description = description;
    }

    public Course(String title, String description, Teacher owner) {
        this.title = title;
        this.description = description;
        this.owner = owner;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Teacher getOwner() {
        return owner;
    }

    public void setOwner(Teacher owner) {
        this.owner = owner;
    }

  /*  public Set<Student> getStudentSet() {
        return studentSet;
    }

    public void setStudentSet(Set<Student> studentSet) {
        this.studentSet = studentSet;
    }
*/
    @Override
    public String toString() {
        return "Course{" +
                "title='" + title + '\'' +
                ", description='" + description + '\'' +
                ", owner=" + owner +

                '}';
    }
}
