package ua.taxi.test.model;

import javax.persistence.*;
import java.util.Date;

/**
 * Created by andrii on 09.07.16.
 */
@Entity
@Table(name = "Students")
public class Student extends IdAutoGeneratedEntity{


    @Column(name = "student", nullable = false, length = 20 )
    private String name;

    @Column
    private double rank;

    @Enumerated(EnumType.STRING)
    private StudentType studentType;

    @Temporal(TemporalType.DATE)
    private Date birth;

    @Transient
    transient private String tempAcces;

    public Student() {
    }

    public Student(String name, double rank, StudentType studentType, Date birth, String tempAcces) {
        this.name = name;
        this.rank = rank;
        this.studentType = studentType;
        this.birth = birth;
        this.tempAcces = tempAcces;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public double getRank() {
        return rank;
    }

    public void setRank(double rank) {
        this.rank = rank;
    }

    public StudentType getStudentType() {
        return studentType;
    }

    public void setStudentType(StudentType studentType) {
        this.studentType = studentType;
    }

    public Date getBirth() {
        return birth;
    }

    public void setBirth(Date birth) {
        this.birth = birth;
    }

    public String getTempAcces() {
        return tempAcces;
    }

    public void setTempAcces(String tempAcces) {
        this.tempAcces = tempAcces;
    }

    @Override
    public String toString() {
        return "Student{" +
                "id=" + getId() +
                ", name='" + name + '\'' +
                ", rank=" + rank +
                ", studentType=" + studentType +
                ", birth=" + birth +
                ", tempAcces='" + tempAcces + '\'' +
                '}';
    }
}
