package ua.taxi.test.model;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by andrii on 09.07.16.
 */

@Entity
@Table(name = "teachers")
public class Teacher extends IdAutoGeneratedEntity {

    private String name;
    private int level;

    @OneToMany(mappedBy = "owner", cascade = {CascadeType.PERSIST}, fetch = FetchType.LAZY)
    private List<Course> courseList = new ArrayList<>();

    public Teacher() {

    }

    public Teacher(int level, String name) {
        this.level = level;
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getLevel() {
        return level;
    }

    public void setLevel(int level) {
        this.level = level;
    }

    public List<Course> getCourseList() {
        return courseList;
    }

    public void setCourseList(List<Course> courseList) {
        this.courseList = courseList;
    }

    @Override
    public String toString() {
        return "Teacher{" +
                "id=" + getId() +
                "name='" + name + '\'' +
                ", level=" + level +
                '}';
    }
}
